In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"E:\AARAV\Infotact-DS-ML\Project-1-Predictive-Maintenance\data\processed\baseline_features.csv")

df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,...,air_temp_std_10,process_temp_std_10,rpm_std_10,torque_std_10,tool_wear_std_10,air_temp_var_10,process_temp_var_10,rpm_var_10,torque_var_10,tool_wear_var_10
0,10,M14869,M,298.5,309.0,1741,28.0,21,0,0,...,0.128668,0.134990,113.060652,6.826655,6.834553,0.016556,0.018222,12782.711111,46.603222,46.711111
1,11,H29424,H,298.4,308.9,1782,23.9,24,0,0,...,0.139841,0.152388,140.100004,8.377722,6.988880,0.019556,0.023222,19628.011111,70.186222,48.844444
2,12,H29425,H,298.6,309.1,1423,44.3,29,0,0,...,0.183787,0.200278,138.545460,8.179622,7.734483,0.033778,0.040111,19194.844444,66.906222,59.822222
3,13,M14872,M,298.6,309.1,1339,51.1,34,0,0,...,0.202485,0.213177,153.055582,8.459899,8.769265,0.041000,0.045444,23426.011111,71.569889,76.900000
4,14,M14873,M,298.6,309.2,1742,30.0,37,0,0,...,0.217307,0.236878,162.150684,8.798131,9.569047,0.047222,0.056111,26292.844444,77.407111,91.566667

In [3]:
df.shape

(9991, 29)

In [4]:
df.columns

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF',
       'air_temp_mean_10', 'process_temp_mean_10', 'rpm_mean_10',
       'torque_mean_10', 'tool_wear_mean_10', 'air_temp_std_10',
       'process_temp_std_10', 'rpm_std_10', 'torque_std_10',
       'tool_wear_std_10', 'air_temp_var_10', 'process_temp_var_10',
       'rpm_var_10', 'torque_var_10', 'tool_wear_var_10'],
      dtype='str')

In [5]:
df["timestamp"] = pd.date_range(start="2026-01-01",periods=len(df),freq="min")

df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,...,process_temp_std_10,rpm_std_10,torque_std_10,tool_wear_std_10,air_temp_var_10,process_temp_var_10,rpm_var_10,torque_var_10,tool_wear_var_10,timestamp
0,10,M14869,M,298.5,309.0,1741,28.0,21,0,0,...,0.134990,113.060652,6.826655,6.834553,0.016556,0.018222,12782.711111,46.603222,46.711111,2026-01-01 00:00:00
1,11,H29424,H,298.4,308.9,1782,23.9,24,0,0,...,0.152388,140.100004,8.377722,6.988880,0.019556,0.023222,19628.011111,70.186222,48.844444,2026-01-01 00:01:00
2,12,H29425,H,298.6,309.1,1423,44.3,29,0,0,...,0.200278,138.545460,8.179622,7.734483,0.033778,0.040111,19194.844444,66.906222,59.822222,2026-01-01 00:02:00
3,13,M14872,M,298.6,309.1,1339,51.1,34,0,0,...,0.213177,153.055582,8.459899,8.769265,0.041000,0.045444,23426.011111,71.569889,76.900000,2026-01-01 00:03:00
4,14,M14873,M,298.6,309.2,1742,30.0,37,0,0,...,0.236878,162.150684,8.798131,9.569047,0.047222,0.056111,26292.844444,77.407111,91.566667,2026-01-01 00:04:00

In [6]:
external_df = pd.DataFrame()

external_df["timestamp"] = df["timestamp"]

In [7]:
external_df["ambient_temperature"] = (df["Process temperature [K]"] + np.random.normal(0, 0.5, len(df)))
external_df["load_density"] = (df["Torque [Nm]"] / 100)

In [8]:
external_df.head()

            timestamp  ambient_temperature  load_density
0 2026-01-01 00:00:00           308.618282         0.280
1 2026-01-01 00:01:00           309.102469         0.239
2 2026-01-01 00:02:00           308.751006         0.443
3 2026-01-01 00:03:00           309.768583         0.511
4 2026-01-01 00:04:00           308.208461         0.300

In [9]:
fused_df = pd.merge(df,external_df,on="timestamp",how="inner")

fused_df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,...,torque_std_10,tool_wear_std_10,air_temp_var_10,process_temp_var_10,rpm_var_10,torque_var_10,tool_wear_var_10,timestamp,ambient_temperature,load_density
0,10,M14869,M,298.5,309.0,1741,28.0,21,0,0,...,6.826655,6.834553,0.016556,0.018222,12782.711111,46.603222,46.711111,2026-01-01 00:00:00,308.618282,0.280
1,11,H29424,H,298.4,308.9,1782,23.9,24,0,0,...,8.377722,6.988880,0.019556,0.023222,19628.011111,70.186222,48.844444,2026-01-01 00:01:00,309.102469,0.239
2,12,H29425,H,298.6,309.1,1423,44.3,29,0,0,...,8.179622,7.734483,0.033778,0.040111,19194.844444,66.906222,59.822222,2026-01-01 00:02:00,308.751006,0.443
3,13,M14872,M,298.6,309.1,1339,51.1,34,0,0,...,8.459899,8.769265,0.041000,0.045444,23426.011111,71.569889,76.900000,2026-01-01 00:03:00,309.768583,0.511
4,14,M14873,M,298.6,309.2,1742,30.0,37,0,0,...,8.798131,9.569047,0.047222,0.056111,26292.844444,77.407111,91.566667,2026-01-01 00:04:00,308.208461,0.300

In [10]:
fused_df.columns

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF',
       'air_temp_mean_10', 'process_temp_mean_10', 'rpm_mean_10',
       'torque_mean_10', 'tool_wear_mean_10', 'air_temp_std_10',
       'process_temp_std_10', 'rpm_std_10', 'torque_std_10',
       'tool_wear_std_10', 'air_temp_var_10', 'process_temp_var_10',
       'rpm_var_10', 'torque_var_10', 'tool_wear_var_10', 'timestamp',
       'ambient_temperature', 'load_density'],
      dtype='str')

In [11]:
fused_df.to_csv(r"E:\AARAV\Infotact-DS-ML\Project-1-Predictive-Maintenance\data\processed\context_fused_dataset.csv",index=False)

external_df.to_csv(r"E:\AARAV\Infotact-DS-ML\Project-1-Predictive-Maintenance\data\external\external_context.csv")