In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv(r"E:\AARAV\Infotact-DS-ML\Project-1-Predictive-Maintenance\data\processed\week2_final_features.csv")

df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,...,tool_wear_var_10,timestamp,ambient_temperature,load_density,temperature_difference,temperature_ratio,load_stress,rpm_torque_interaction,ambient_temp_mean_10,load_density_mean_10
0,19,H29432,H,298.8,309.2,1306,54.5,50,0,0,...,94.400000,2026-01-01 00:09:00,308.229670,0.545,10.4,1.034806,29.7025,71177.0,308.870825,0.3920
1,20,M14879,M,298.9,309.3,1632,32.5,55,0,0,...,90.622222,2026-01-01 00:10:00,308.691718,0.325,10.4,1.034794,10.5625,53040.0,308.878169,0.3965
2,21,H29434,H,298.9,309.3,1375,42.7,58,0,0,...,83.822222,2026-01-01 00:11:00,308.795425,0.427,10.4,1.034794,18.2329,58712.5,308.847464,0.4153
3,22,L47201,L,298.8,309.3,1450,44.8,63,0,0,...,89.111111,2026-01-01 00:12:00,309.226411,0.448,10.5,1.035141,20.0704,64960.0,308.895005,0.4158
4,23,M14882,M,298.9,309.3,1581,30.7,65,0,0,...,95.655556,2026-01-01 00:13:00,309.619938,0.307,10.4,1.034794,9.4249,48536.7,308.880140,0.3954

In [4]:
df.shape

(9982, 38)

In [5]:
df.columns

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF',
       'air_temp_mean_10', 'process_temp_mean_10', 'rpm_mean_10',
       'torque_mean_10', 'tool_wear_mean_10', 'air_temp_std_10',
       'process_temp_std_10', 'rpm_std_10', 'torque_std_10',
       'tool_wear_std_10', 'air_temp_var_10', 'process_temp_var_10',
       'rpm_var_10', 'torque_var_10', 'tool_wear_var_10', 'timestamp',
       'ambient_temperature', 'load_density', 'temperature_difference',
       'temperature_ratio', 'load_stress', 'rpm_torque_interaction',
       'ambient_temp_mean_10', 'load_density_mean_10'],
      dtype='str')

In [6]:
target = "Machine failure"

X = df.drop(target,axis=1)
y = df[target]

In [7]:
X = X.select_dtypes(include=np.number)

In [8]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=200,random_state=42)

model.fit(X,y)

RandomForestClassifier(n_estimators=200, random_state=42)

In [9]:
importance = pd.DataFrame({"Feature": X.columns, "Importance": model.feature_importances_})

importance = importance.sort_values(by="Importance",ascending=False)

importance

                    Feature  Importance
7                       HDF    0.199468
9                       OSF    0.160887
8                       PWF    0.107144
6                       TWF    0.095670
31   rpm_torque_interaction    0.072502
3    Rotational speed [rpm]    0.051817
30              load_stress    0.046832
4               Torque [Nm]    0.043431
27             load_density    0.040690
5           Tool wear [min]    0.026008
29        temperature_ratio    0.025251
15        tool_wear_mean_10    0.022296
28   temperature_difference    0.018119
11         air_temp_mean_10    0.006747
0                       UDI    0.005771
18               rpm_std_10    0.005650
12     process_temp_mean_10    0.005466
33     load_density_mean_10    0.005459
23               rpm_var_10    0.004965
19            torque_std_10    0.004931
1       Air temperature [K]    0.004862
26      ambient_temperature    0.004808
24            torque_var_10    0.004796
32     ambient_temp_mean_10    0.004778
13              rpm_mean_10    0.004369
14           torque_mean_10    0.004283
25         tool_wear_var_10    0.003889
20         tool_wear_std_10    0.003431
2   Process temperature [K]    0.003347
22      process_temp_var_10    0.003289
21          air_temp_var_10    0.003208
16          air_temp_std_10    0.002909
17      process_temp_std_10    0.002719
10                      RNF    0.000209

In [10]:
top_features = importance.head(15)["Feature"]

top_features

7                        HDF
9                        OSF
8                        PWF
6                        TWF
31    rpm_torque_interaction
3     Rotational speed [rpm]
30               load_stress
4                Torque [Nm]
27              load_density
5            Tool wear [min]
29         temperature_ratio
15         tool_wear_mean_10
28    temperature_difference
11          air_temp_mean_10
0                        UDI
Name: Feature, dtype: str

In [11]:
final_df = df[list(top_features) + ["Machine failure"]]

In [12]:
final_df.to_csv(r"E:\AARAV\Infotact-DS-ML\Project-1-Predictive-Maintenance\data\processed\model_ready_dataset.csv",index=False)