In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"E:\AARAV\Infotact-DS-ML\Project-1-Predictive-Maintenance\data\processed\model_ready_dataset.csv")

df.head()

,HDF,OSF,PWF,TWF,rpm_torque_interaction,Rotational speed [rpm],load_stress,Torque [Nm],load_density,Tool wear [min],temperature_ratio,tool_wear_mean_10,temperature_difference,air_temp_mean_10,UDI,Machine failure
0,0,0,0,0,71177.0,1306,29.7025,54.5,0.545,50,1.034806,36.8,10.4,298.60,19,0
1,0,0,0,0,53040.0,1632,10.5625,32.5,0.325,55,1.034794,40.2,10.4,298.64,20,0
2,0,0,0,0,58712.5,1375,18.2329,42.7,0.427,58,1.034794,43.6,10.4,298.69,21,0
3,0,0,0,0,64960.0,1450,20.0704,44.8,0.448,63,1.035141,47.0,10.5,298.71,22,0
4,0,0,0,0,48536.7,1581,9.4249,30.7,0.307,65,1.034794,50.1,10.4,298.74,23,0

In [3]:
df.shape

(9982, 16)

In [4]:
df.isnull().sum()

HDF                       0
OSF                       0
PWF                       0
TWF                       0
rpm_torque_interaction    0
Rotational speed [rpm]    0
load_stress               0
Torque [Nm]               0
load_density              0
Tool wear [min]           0
temperature_ratio         0
tool_wear_mean_10         0
temperature_difference    0
air_temp_mean_10          0
UDI                       0
Machine failure           0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df = df.drop_duplicates()

In [7]:
df["Machine failure"].value_counts()

Machine failure
0    9643
1     339
Name: count, dtype: int64

In [8]:
summary = pd.DataFrame({
                        "Rows":[df.shape[0]],
                        "Columns":[df.shape[1]],
                        "Missing Values":[df.isnull().sum().sum()],
                        "Duplicate Rows":[df.duplicated().sum()]
                    })
summary

   Rows  Columns  Missing Values  Duplicate Rows
0  9982       16               0               0