In [1]:
import pandas as pd
import numpy as np

import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score

In [2]:
df = pd.read_csv(r"E:\AARAV\Infotact-DS-ML\Project-1-Predictive-Maintenance\data\processed\model_ready_dataset.csv")

df.head()

   HDF  OSF  PWF  ...  air_temp_mean_10  UDI  Machine failure
0    0    0    0  ...            298.60   19                0
1    0    0    0  ...            298.64   20                0
2    0    0    0  ...            298.69   21                0
3    0    0    0  ...            298.71   22                0
4    0    0    0  ...            298.74   23                0

[5 rows x 16 columns]

In [3]:
X = df.drop("Machine failure", axis=1)

y = df["Machine failure"]

In [4]:
X.columns = (
    X.columns
    .str.replace("[","",regex=False)
    .str.replace("]","",regex=False)
    .str.replace("{","",regex=False)
    .str.replace("}","",regex=False)
    .str.replace(":","",regex=False)
    .str.replace(",","",regex=False)
)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [6]:
model = joblib.load(r"E:\AARAV\Infotact-DS-ML\Project-1-Predictive-Maintenance\models\final_lightgbm_model.pkl")

In [7]:
original_prediction = model.predict(X_test)

original_f1 = f1_score(y_test, original_prediction)

original_f1

np.float64(0.951048951048951)

In [8]:
def add_noise(data, noise_level):
    noisy_data = data.copy()

    noise = np.random.normal(loc=0, scale=noise_level, size=noisy_data.shape)

    noisy_data += noise

    return noisy_data

In [9]:
noise_results = []

for level in [0.01,0.05,0.1]:
    noisy_test = add_noise(X_test, noise_level=level)

    prediction = model.predict(noisy_test)

    noise_results.append({
        "Noise Level": level,
        "F1 Score": f1_score(y_test, prediction)
    })

In [10]:
noise_df = pd.DataFrame(noise_results)

noise_df

   Noise Level  F1 Score
0         0.01  0.071055
1         0.05  0.070796
2         0.10  0.072149

In [11]:
noise_df.to_csv(r"E:\AARAV\Infotact-DS-ML\Project-1-Predictive-Maintenance\data\processed\noise_sensitivity_results.csv", index=False)